### ISSUE TITLE
system UI FC when enabling "fix huge space under QS header" on LP

### ISSUE THREAD

**Issue by mranzy** [wasdennnoch/AndroidN-ify#1202]
Here is the logcat:
[logcatonboot1.txt](https://github.com/wasdennnoch/AndroidN-ify/files/587321/logcatonboot1.txt)

**Comment by licaon-kter** [comment]
Yep, here too on Xperia 5.1.1

@mranzy How did you get that log?

**Comment by Freewander10** [comment]
Same here.

**Comment by paphonbth** [comment]
Should be fixed with 46cde8f.

**Comment by licaon-kter** [comment]
@paphonbth That commit mentions another issue. This issue unfortunately is not fixed in build 772.

**Comment by pwrusr** [comment]
@paphonbth #1192

**Comment by paphonbth** [comment]
Then I need a new log. That commit mentions #1203 but also should fix this too.

**Comment by mranzy** [comment]
@paphonbth there's still system UI crash when enabling it on the new version as well (774)
And here is the logcat for that: 
[logcatonboot2.txt](https://github.com/wasdennnoch/AndroidN-ify/files/587805/logcatonboot2.txt)

**Comment by mranzy** [comment]
It's fixed now 👍
