### ISSUE TITLE
QS row not showing

### ISSUE THREAD

**Issue by sherrysakura** [wasdennnoch/AndroidN-ify#221]

**Comment by sherrysakura** [comment]
Device: Motorola X Pro XT1115 running Android 5.0.2 AOSP based.
http://imgur.com/FxEn0Rc

**Comment by wasdennnoch** [comment]
Can you please post your Xposed log here?

**Comment by sherrysakura** [comment]
Hi wasdennnoch, thanks for the reply.
The current distribution already fixed the overlapping problem, but when scrolling down from the notification bar, tiles still don't appear.
Below is the goole drive link to the xposed log, see if it works for you. Thank you again for promt reply.
https://drive.google.com/file/d/0B9zHLYyJbdlVVzNVd1FEYlNfTjQ/view?usp=drivesdk

**Comment by wasdennnoch** [comment]
Is your ROM deodexed? If so, please post your SystemUI.apk here. If not I'll have to build you some test versions.

**Comment by sherrysakura** [comment]
https://drive.google.com/file/d/0B9zHLYyJbdlVd2hWOHBKdV9BTEU/view?usp=drivesdk

Above is my systemui.apk, only slightly modified 4G/LTE signal pics myself. Device very similar to Nexus 6.

**Comment by wasdennnoch** [comment]
Ah, it's odexed. Can you please install this test version and send me the log? Remember uninstalling the previous version first.
http://www.mediafire.com/download/n8alh3ijbn4bcn6/Android_N-ify_test.apk

**Comment by sherrysakura** [comment]
Screenshot: https://drive.google.com/file/d/0B9zHLYyJbdlVUDhEaVQtUTRTYkk/view?usp=drivesdk
Log: https://drive.google.com/file/d/0B9zHLYyJbdlVaEN1Y0otMWhuWDg/view?usp=drivesdk

Generally works, text no longer overlapping as the public build 153. But still no header tiles.

**Comment by wasdennnoch** [comment]
I've sent a permission request to access this log file...

**Comment by sherrysakura** [comment]
Done. Sorry for inconvenience.

**Comment by wasdennnoch** [comment]
Try this version please: http://www.mediafire.com/download/sptlq52lrl16v1q/Android_N-ify_test_2.apk

**Comment by wasdennnoch** [comment]
Did you get and test the test version?

**Comment by wasdennnoch** [comment]
As there is no response I'll close this for now.

**Comment by sherrysakura** [comment]
Hi wasdennnoch, sorry for late reply.
There's still some issues.
1. Still no header tiles.
2. Comflicts with Xposed plugin "Status Bar Scroll to Top"

Log: https://drive.google.com/open?id=0B9zHLYyJbdlVaWlNNW13eU1zZkk

**Comment by wasdennnoch** [comment]
Can you please try out the lastet automated build? I added another attempt I forgot before. The build shows as failed, but you can still download the app-debug.apk that should install without any problems.

**Comment by sherrysakura** [comment]
Hi wasdennoch, the #209 build brought in the QS tile, but there's still some minor issues of the quick settings icons. Any chance to fix that? Although I haven't tried the latest build, but would you mind looking at it?

Log: https://drive.google.com/open?id=0B9zHLYyJbdlVdExZdW9zUUlBN0U
Screenshot: http://i.imgur.com/2P7huSb.png?1

**Comment by wasdennnoch** [comment]
In 3f561d90217332cee735e265f54713e4304b570a I added an option to use the old QS positioning method, that should fix it for now.

**Comment by sherrysakura** [comment]
After installing the lastest mod, there's still the same problem.
Log: https://drive.google.com/open?id=0B9zHLYyJbdlVWHphaVJHTVRwR1k
And the old "clear all" button was replaced with "clear all" words, regardless the related setting is.

Any suggestions wasdennnoch please?

**Comment by wasdennnoch** [comment]
Just want to note that a module with the package "liubaoyua.customtext" is spamming the log with a NPE.
Are you sure that you activated the option and rebooted? (Status bar header > Alternative QS loading method).

**Comment by sherrysakura** [comment]
Yes wasdennnoch, I tried several times but still the same problem. I will disable the customtext module and give you another log later.

**Comment by teapack** [comment]
I also gave the issue with QS row not appearing. Device: LG G3 d855 (32GB version), ROM: AOSP based 6.0.1 (http://forum.xda-developers.com/lg-g3/development/rom-xenonhd-6-0-t3240119), Android N-ify version 0.2.0.

Screenshot of the problem: https://drive.google.com/file/d/0B05KOFwx05vaaXlRVkNZdlo2UzA/view?usp=drivesdk
Screenshot of Status bar header settings in Android N-ify app: https://drive.google.com/file/d/0B05KOFwx05vaakJ3OEt0SWlfdWc/view?usp=drivesdk
Xposed log: https://drive.google.com/file/d/0B05KOFwx05vaN0duSHliTmJidlE/view?usp=drivesdk
SystemUI apk: https://drive.google.com/file/d/0B05KOFwx05vadTdtVFBQeXZSajg/view?usp=drivesdk

Let me know if you need any help with testing, debugging, or more info. Other than that, the app is working fine.

**Comment by wasdennnoch** [comment]
I've sent permission requests for the last three files.

**Comment by teapack** [comment]
I granted you the permissions few minutes after you requested them.

However, I'm thinking that the issue might be related to my ROM - it's slightly different from vanilla AOSP. I'll clone and build your project on my computer and try to debug it on my device and let you know if I figure something out.

Something weird happened, by the way. Yesterday, my SystemUI app crashed (the dialog saying something like "Unfortunately, SystemUI stopped." appeared), and then, after it (the SystemUI app) restarted, the QS row appeared for the first time. It disappeared after a reboot. I wasn't able to reproduce it. Force stopping SystemUI app from settings doesn't help, stopping the SystemUI process from terminal (or via adb) doesn't help either (although I now realized I didn't try SIGKILL, I only tried SIGTERM).

**Comment by iSaidyiu** [comment]
Hi there, I also have suffered from the above problem since long time ago, and I have asked for help on xda a couple of times before posting this on Github. My problem is no matter stable or beta and the combination of the tweaks in the app cannot make ny QS row tiles shown up in the status bar pullldown,

Screenshots+SystemUI.apk+XposedLog
https://drive.google.com/folderview?id=0B7bVa2veAvAcS29lRHRmRGJlR1U&usp=sharing

**Comment by wasdennnoch** [comment]
@teapack There are no errors in the log and I can't find anything different in the SystemUI. You are running a stock ROM? It has a QSDragPanel which CM has too, but that shouldn't be a problem.

@iSaidyiu The first crash got fixed with 94538d3bb1ef81cf72c295e5916075763d90eadc, now the QouckQS should be showing too. There's still another crash that I have to look into.

**Comment by wasdennnoch** [comment]
Second crash should be fixed too (05755bab21d44587102b48138a7193c9cf44d0fd)

**Comment by iSaidyiu** [comment]
Sorry but I am quite a newbie in Github, may I know what I need to do with these two codes? Do I need to compile it into the corresponding file in the apk?

**Comment by wasdennnoch** [comment]
You don't need to do anything except for installing the newest version, those code snippets are the things I changed ;)

**Comment by iSaidyiu** [comment]
Is it released yet cuz' after I install the latest version #314 beta I still found nothing on the QS row…

**Comment by iSaidyiu** [comment]
Sorry, #315 it is.

**Comment by wasdennnoch** [comment]
Then I need new logs

**Comment by iSaidyiu** [comment]
I opened a new folder under the shared folder sent to you before.

**Comment by wasdennnoch** [comment]
I had a look at your SystemUI code and I don't thing it's possible to add support for your ROM; they heavily chaged QS- and notification related code; they don't even store a reference to the tiles anymore the module could access, so it's practically impossible for the module to get the tiles and display them in the header. Sorry :(

**Comment by iSaidyiu** [comment]
Okay…
Anyway thanks for your help!

**Comment by iSaidyiu** [comment]
Well I am thinking. Is it possible to add an independent set of QS provided by the app so people using hevaily moded rom can have an alternative way to choose their QS row icons which may different from the OS one?
