### ISSUE TITLE
Edit button crash on Candy 3.0

### ISSUE THREAD

**Issue by SlimShadys** [wasdennnoch/AndroidN-ify#411]
I'm using the very lastest version of CandySiX and the lastest version of AndroidN-Ify.
As soon as I press the back button to exit the EDIT mode in Notifications, the UI crashes..
Log: http://hastebin.com/izimipuxif.avrasm (I guess it can't find a method?)
Thank you :)

**Comment by wasdennnoch** [comment]
Indeed, Candy replaced the Tunable with a ContentObserver ( https://github.com/CandyRoms/frameworks_base/blob/c6/packages/SystemUI/src/com/android/systemui/statusbar/phone/QSTileHost.java#L370 ) :)

**Comment by SlimShadys** [comment]
Can it be fixed or it is impossible? :)

**Comment by wasdennnoch** [comment]
It should be easy (I hope)

**Comment by wasdennnoch** [comment]
Should be fixed with 922b14bf824d359a934c24b4327ccb74b05efba0. They are still using a method from Lollipop but the module tried to call the Marshmallow one.

**Comment by SlimShadys** [comment]
Nope. Still crash :)
hastebin.com/zikixolage.avrasm

**Comment by wasdennnoch** [comment]
Whoops, forgot to change one line. 111a66255848d57330f177f6f7c0b1f931c0e8b8 should fix that crash :)

**Comment by SlimShadys** [comment]
Still crash omg @CandyRoms xD
www.hastebin.com/zuliseniyo.avrasm

**Comment by wasdennnoch** [comment]
Wow. They really like LP code. dc18d56db3217054b8e39bd0f15974ae3f9ec303

**Comment by SlimShadys** [comment]
I'm out bruh.
www.hastebin.com/ilefurobax.vbs

**Comment by wasdennnoch** [comment]
Grargh c1fcfc6211bfb3501d007b3834ed41a1ec375441

**Comment by SlimShadys** [comment]
Now it works! Thanks! :)
But animations are still broken and Xposed can't read preference file..Never happened :P

**Comment by wasdennnoch** [comment]
The Xposed prefs issue could be because of the many recent reinstalls, try uninstalling it, reboot (the UI looks completely weird after that... so... default :P) and install again. The animations are borken for many people, including me.
