### ISSUE TITLE
Some requests for blisspop

### ISSUE THREAD

**Issue by hrithikb** [wasdennnoch/AndroidN-ify#567]
Can you change the recent apps style as the stock i mean eliminate the curved edges (as shown

**Comment by hrithikb** [comment]
*picture) https://drive.google.com/file/d/0B0NJb0mKnh5QcGdQMXI0VXFneVE/view?usp=drivesdk

Its only in blisspop and i ask you for this because you resized the app review page

**Comment by hrithikb** [comment]
And also the quick action button on notification is not coloured because of blisspop it's a request pls  change it!
https://drive.google.com/file/d/0B0NJb0mKnh5QX25leFJveDVwYTg/view?usp=drivesdk
It's the describing screenshot?

**Comment by hrithikb** [comment]
And also quick toggles in header is bigger than the original!

**Comment by wasdennnoch** [comment]
I fixed the corner radius, the large header toggles are already discussed in another issue, for the action button I'd need your Xposed log.

**Comment by hrithikb** [comment]
https://drive.google.com/file/d/0B0NJb0mKnh5QbG5ramstbkJPbWs/view?usp=drivesdk
Here we go

**Comment by hrithikb** [comment]
https://drive.google.com/file/d/0B0NJb0mKnh5QbllIcUJicmF2dDg/view?usp=drivesdk
After the latest snapshot the corner radius of app overview is still showing curved! Only first 2 3 app is in square shape

**Comment by hrithikb** [comment]
Sir, check for this also please!

**Comment by wasdennnoch** [comment]
Ooops, my bad with the button color, fixed with 9a18abe22aa5e9c66b19d6b389e312c37374c85d.

**Comment by wasdennnoch** [comment]
Recents radius should be fixed with cf770a4f6e5a4a9e2cca22dcdeaa0df01184e609

**Comment by hrithikb** [comment]
Button color still not fixed

**Comment by hrithikb** [comment]
And corner radius is also same as but better than the original curved as in blisspop

**Comment by wasdennnoch** [comment]
Pushed a fix again, now the corner radius should work (at leas at the bottom corners...), again need a log for the button color.

**Comment by hrithikb** [comment]
https://drive.google.com/file/d/0B0NJb0mKnh5QUmpSMERSNGphZm8/view?usp=drivesdk
After the latest version the module is not activated! I activated it already

**Comment by wasdennnoch** [comment]
Well, have you rebooted?

**Comment by hrithikb** [comment]
I've done everything but the module is not activating plz help

**Comment by hrithikb** [comment]
I revert back to the previous version also but nothing happened!

**Comment by wasdennnoch** [comment]
Untich and tick the checkbox in the installer. Then reboot.

**Comment by hrithikb** [comment]
Done, already not working

**Comment by hrithikb** [comment]
Every modules are working good only n ify is jot working

**Comment by hrithikb** [comment]
Every modules are working good only n ify is not working

**Comment by hrithikb** [comment]
If i soft reboot my phone module works but after full reboot it does not!! Any help sir??
