### ISSUE TITLE
a few things on the op3. oos3.2.1

### ISSUE THREAD

**Issue by stooyleown** [wasdennnoch/AndroidN-ify#625]
when tapping the the pencil at top right, systemUI resets
[tapping pencil.txt](https://github.com/wasdennnoch/AndroidN-ify/files/380532/tapping.pencil.txt)

Hide edit tiles button toggle under hide header items should hide the pencil correct?  If it should, its not doing so. 
Also when tapping the edit icon(the actually edit word, bottom right ) nothing happens.
[tapping edit.txt](https://github.com/wasdennnoch/AndroidN-ify/files/380535/tapping.edit.txt)

If you need xposed logs also let me know.  The 2 logs posted are via logcat. xposed ver 86.2 systemless by topjohnwu

**Comment by stooyleown** [comment]
Sorry, forgot to mention. Using #469

**Comment by stooyleown** [comment]
Also forgot to mention,with QS editor disabled, tapping pencil doesn't restart systemui.

**Comment by wasdennnoch** [comment]
Fixed with 7ac4139af0cd782058030c8d1c144fc9c8e71179 and  c09cc19794032a2f4f72c4898fe3011ae1697546

**Comment by stooyleown** [comment]
What option should hide the pencil?  In hide header items, I have first two options enabled, but pencil is still showing.  Also it is still click able, and restarts systemui when we editor is enabled. Not next to PC to logcat it.

**Comment by wasdennnoch** [comment]
The OOS3 SystemUI I used has the same view name as the OOS2 one, the only change is an additional reset button that I hid too. It it's not working I need another deodexed SystemUI to decompile and check.

**Comment by stooyleown** [comment]
You need it from an op3 again? Same as I did before?  I can follow pap's way of doing it if what I sent before wasn't correct.

**Comment by wasdennnoch** [comment]
Oh yes, it was your SystemUI. Well, It should work, they didn't change any variable names. Just make sure that the preference file is readable and that you reboot after a change.

**Comment by stooyleown** [comment]
Well, just got home.  Latest version, the qs editor button(word button) works now.  Still can't hidethe pencil and when tapping it with qs editor on, systemui reboots.  I'll logcat it see if it's any different than previous.

**Comment by stooyleown** [comment]
[updated-pencil-tap.txt](https://github.com/wasdennnoch/AndroidN-ify/files/382470/updated-pencil-tap.txt)

**Comment by wasdennnoch** [comment]
Shoud be fixed again.
