### ISSUE TITLE
Wifi and Bluetooth tile opening in setting in single click

### ISSUE THREAD

**Issue by AniketDhoke** [wasdennnoch/AndroidN-ify#649]
build #391

**Comment by hrithikb** [comment]
When this'll be fixed sir?

**Comment by wasdennnoch** [comment]
You opened this 5 hours ago, it's almost midnight here, and you already ask when this is going to be fixed. Ok. 

Simple answer: I don't know. I don't know what is causing this behavior yet, I'll have a look at the Android source tomorrow, if that doesn't help I'll add some more debugging code and request more logs. You have to be patient, I'm a humam too with human needs and habits that have to be fulfilled.

**Comment by hrithikb** [comment]
Oh I'm extremely sorry sir, i didn't know that there's midnight too! I admire your hard work sir please don't get me wrong.

**Comment by wasdennnoch** [comment]
Fixed with a46166d0a208cae23c05cf5e6679e0be13905579

**Comment by hrithikb** [comment]
Not fixed, sir its not working in header and as well as qs panel!

**Comment by hrithikb** [comment]
The toggle which don't have detail view, are working fine but the one with detail view are not working!

**Comment by hrithikb** [comment]
Sir toggle in qs panel are working but in header its not

**Comment by wasdennnoch** [comment]
Anything changed with the latest build? Also please add a new Xposed log if something's broken.

**Comment by hrithikb** [comment]
Well, after the latest build nothing changed and one new thing appeared, there's a ghost touch in bw settings toggle button and avatar.
Here's the log:
https://drive.google.com/file/d/0B0NJb0mKnh5QWFNvX3owSmdoWE0/view?usp=drivesdk
