### ISSUE TITLE
Toggles are not working

### ISSUE THREAD

**Issue by hrithikb** [wasdennnoch/AndroidN-ify#661]
The Bluetooth, data, and wifi toggles are not working in header as well as in qs panel also they don't show detail view and when long pressing them nothing happened!

**Comment by hrithikb** [comment]
https://drive.google.com/file/d/0B0NJb0mKnh5QQXJSbnhYUFpQLTA/view?usp=drivesdk
Xposed logs

**Comment by wasdennnoch** [comment]
Long click got fixed with 9db0b33fef87e2e354578543c5297c4b91103bd9, please test for the other issue you mentioned on build 513

**Comment by hrithikb** [comment]
Still not fixed sir on latest #522 and also large icons in header
