### ISSUE TITLE
Various titles problem on CM12.1

### ISSUE THREAD

**Issue by xpduyson** [wasdennnoch/AndroidN-ify#684]
1. Wifi, mobile network and bluetooth toogle title in QS header not working: https://gist.github.com/xpduyson/f9b4569639866c847b1530a6f3b906f6
2. Long click Wifi, mobile network and bluetooth on explaned QS not working: https://gist.github.com/xpduyson/1153f69f64b4cf1314d3df29176486f1
3. Single click mobile network title on explaned QS not working: https://gist.github.com/xpduyson/e88b7a56e6025088da17ed7fc57661e4

**Comment by hrithikb** [comment]
Facing same also qs collapse every time when pressing any toggle which opens detail view
It means can't open detail view!

**Comment by xpduyson** [comment]
@hrithikb You can disable "Enable QS Editor" as a temporary fix

**Comment by hrithikb** [comment]
When I'm doing that then no battery tile is coming, is there any other fix?

**Comment by xpduyson** [comment]
I think the development of this module focus mainly on CM13, so I think dev won't fix it soon

**Comment by hrithikb** [comment]
@xpduyson No they'll fix it don't worry, this module is also for lollipop so we just have to wait a little, they've done a great job for LP phones also!

**Comment by wasdennnoch** [comment]
Which ROM are you on?

**Comment by hrithikb** [comment]
On stock cm12.1, sir when i was on aicp or any other cm12.1 based rom then the qs panel do not collapse after pressing wifi or Bluetooth tile or any other with tile with detail view but for some reason i changed my rom

**Comment by wasdennnoch** [comment]
Oh, it even says it in the title.

**Comment by hrithikb** [comment]
Yes, please sir do something for this because i can't install any MM rom in my phone because there is no such rom supports my device.

**Comment by wasdennnoch** [comment]
The crashes in the gists got fixed with the latest commits.

**Comment by hrithikb** [comment]
Sir, not fixed qs panel got collapse every time after pressing the tile with detail view and when pressing the battery tile no details are coming and system ui crashes but when i pressed the edit button then its not crashing but collapsed!

**Comment by wasdennnoch** [comment]
The issues you are mentioned are already open somewhere lese, the main chashes from the gists got fixed. I'll implement another method of handling tile clicks as many ROMs changed many things...
