### ISSUE TITLE
system ui crash after reboot in every 2 ,3second interval

### ISSUE THREAD

**Issue by Androdiver** [wasdennnoch/AndroidN-ify#817]
In your 619 build system ui crash after i reboot my device and its not let me do any this in every to second it crased i hardly manage to save xposed log and disableing your module plaese do somethinn
Here is xposed log
[xposed_error_20160911_001337.log.txt](https://github.com/wasdennnoch/AndroidN-ify/files/465586/xposed_error_20160911_001337.log.txt)

**Comment by wasdennnoch** [comment]
Unfortunately your Xposed log doesn't help me, in case of app crashes you always have to post a logcat. Luckily you can do this from your computer.

**Comment by Androdiver** [comment]
I got the catlog logs its here
[2016-09-11-00-51-30.txt](https://github.com/wasdennnoch/AndroidN-ify/files/465602/2016-09-11-00-51-30.txt)
Now problem getting worsed my system ui stop in every 1 second

**Comment by wasdennnoch** [comment]
Already fixed that one with ef503a8281be21bf3b94a90f340b348535a2d5ec 2 minutes ago :PBuild in progress.

**Comment by Androdiver** [comment]
The problem is still not solved my system ui stopped after reboot

**Comment by wasdennnoch** [comment]
Log again please

**Comment by Androdiver** [comment]
Here is log
[2016-09-11-13-44-41.txt](https://github.com/wasdennnoch/AndroidN-ify/files/466071/2016-09-11-13-44-41.txt)

**Comment by wasdennnoch** [comment]
Should be fixed too, but there aren't any new builds so I'll probably manually build some later.

**Comment by Androdiver** [comment]
I am on build 653 and it not fixed yet did you fix or it takes time
Here is build 653 logs
[xposed_error_20160920_165821.log.txt](https://github.com/wasdennnoch/AndroidN-ify/files/482424/xposed_error_20160920_165821.log.txt)

**Comment by wasdennnoch** [comment]
PLease install this buildd and post your Xposed log after a reboot: http://www.mediafire.com/download/ql1at3f6sd0eil6/Android_N-ify_debug_log_IntentTile.apk

**Comment by Androdiver** [comment]
Here is log after installing debug apk
[xposed_error_20160921_003527.log.txt](https://github.com/wasdennnoch/AndroidN-ify/files/483432/xposed_error_20160921_003527.log.txt)

**Comment by wasdennnoch** [comment]
For some reason the infos I wanted to log aren't in the log, so here's a second attempt: http://www.mediafire.com/download/39wt2elfbg35opg/Android_N-ify_debug_log2_IntentTile.apk

Also 2 things: A custom lockscreen shortcuts module likes to spam the log and - Good Night :)

**Comment by Androdiver** [comment]
Here is xposed log of seconds debud apk 
[xposed_error_20160921_180800.log.txt](https://github.com/wasdennnoch/AndroidN-ify/files/484998/xposed_error_20160921_180800.log.txt)

And also here is catlog 
[2016-09-21-18-06-47.txt](https://github.com/wasdennnoch/AndroidN-ify/files/485004/2016-09-21-18-06-47.txt)

**Comment by BlackGhost12** [comment]
I have that same problem.

**Comment by AK2611** [comment]
I also have same problem

**Comment by wasdennnoch** [comment]
Yay, for some reason your ROM completely removed the long click method. I'll find another solution, in the meanwhile I'll work around this. You won't be able to long click the battery tile, but at least it doesn't crash anymore. (5d34038d82196a5ccc27c4f1b68f4388c5a09a21)
