### ISSUE TITLE
Class not found exception during StatusBarHooks on Lollipop 5.1

### ISSUE THREAD

**Issue by ds84182** [wasdennnoch/AndroidN-ify#835]
[Logs Here](http://hastebin.com/xedeloqeto)

Caused by the latest commit (commit 706a751)

**Comment by ds84182** [comment]
Between Marshmallow and Lollipop MobileSignalController was split from NetworkControllerImpl.java.

[Here is the file during lollipop-mr1-release](https://github.com/android/platform_frameworks_base/blob/lollipop-mr1-release/packages/SystemUI/src/com/android/systemui/statusbar/policy/NetworkControllerImpl.java)

**Comment by paphonbth** [comment]
Should be fixed with #843.

**Comment by ds84182** [comment]
I'm still getting a class not found exception with the latest build, possibly because of some Motorola specific SystemUI tweaks on the Moto X 2013. 

```
09-18 14:33:05.078 E/Xposed ( 1267): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.systemui.statusbar.policy.NetworkControllerImpl$MobileSignalController" on path: DexPathList[[zip file "/system/priv-app/SystemUI/SystemUI.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]] 09-18 14:33:05.078 E/Xposed ( 1267): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56) 09-18 14:33:05.078 E/Xposed ( 1267): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511) 09-18 14:33:05.078 E/Xposed ( 1267): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469) 09-18 14:33:05.078 E/Xposed ( 1267): 	... 25 more 09-18 14:33:05.078 E/Xposed ( 1267): 	Suppressed: java.lang.ClassNotFoundException: Didn't find class "com.android.systemui.statusbar.policy.NetworkControllerImpl$MobileSignalController" on path: DexPathList[[dex file "/data/dalvik-cache/xposed_XResourcesSuperClass.dex"],nativeLibraryDirectories=[/vendor/lib, /system/lib]] 09-18 14:33:05.078 E/Xposed ( 1267): 		at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56) 09-18 14:33:05.078 E/Xposed ( 1267): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:511) 09-18 14:33:05.078 E/Xposed ( 1267): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504) 09-18 14:33:05.078 E/Xposed ( 1267): 		... 26 more 09-18 14:33:05.078 E/Xposed ( 1267): 		Suppressed: java.lang.ClassNotFoundException: com.android.systemui.statusbar.policy.NetworkControllerImpl$MobileSignalController 09-18 14:33:05.078 E/Xposed ( 1267): 			at java.lang.Class.classForName(Native Method) 09-18 14:33:05.078 E/Xposed ( 1267): 			at java.lang.BootClassLoader.findClass(ClassLoader.java:781) 09-18 14:33:05.078 E/Xposed ( 1267): 			at java.lang.BootClassLoader.loadClass(ClassLoader.java:841) 09-18 14:33:05.078 E/Xposed ( 1267): 			at java.lang.ClassLoader.loadClass(ClassLoader.java:504) 09-18 14:33:05.078 E/Xposed ( 1267): 			... 27 more 09-18 14:33:05.078 E/Xposed ( 1267): 		Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
```

**Comment by ds84182** [comment]
Is it possible to just disable the status bar tweaks completely?

**Comment by wasdennnoch** [comment]
Looks like Motorola moved that somewhere else. RIght now you can't disable it, but we can add a toggle to disable the new "Not Connected" icon in the cell tile which causes this issue. If you have a deodexed version of your SystemUI laying around or if you want to try deodexing you can post it here so we can have a look at it.

**Comment by wasdennnoch** [comment]
Should be fixed with b85c10bf01ef4711716430a559f2e705145daf05

**Comment by ds84182** [comment]
Nope, doesn't fix. I'll deodex the SystemUI apk in a sec

**Comment by ds84182** [comment]
Is this OK? https://drive.google.com/file/d/0BzkaO0atYpl3dy01bXZGelpERE0/view?usp=drivesdk

**Comment by ds84182** [comment]
I guess it is OK because smali gives me some output. Seems like Motorola made their own network controller impls.

**Comment by wasdennnoch** [comment]
Aand fixed again, tx for the SystemUI. They just prefixed it with "Motorola". I guess they do it to indicate where they made changes?
