### ISSUE TITLE
Crashing on lollipop

### ISSUE THREAD

**Issue by LosTigeros** [wasdennnoch/AndroidN-ify#859]
Hello. My soc is MT6753

```
09-18 09:54:59.639 E/Xposed  (30569): de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.android.systemui.statusbar.policy.MobileSignalController
09-18 09:54:59.639 E/Xposed  (30569): 	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:64)
09-18 09:54:59.639 E/Xposed  (30569): 	at tk.wasdennnoch.androidn_ify.systemui.statusbar.StatusBarHooks.<init>(StatusBarHooks.java:23)
09-18 09:54:59.639 E/Xposed  (30569): 	at tk.wasdennnoch.androidn_ify.systemui.statusbar.StatusBarHooks.create(StatusBarHooks.java:18)
09-18 09:54:59.639 E/Xposed  (30569): 	at tk.wasdennnoch.androidn_ify.systemui.SystemUIHooks.hookSystemUI(SystemUIHooks.java:45)
09-18 09:54:59.639 E/Xposed  (30569): 	at tk.wasdennnoch.androidn_ify.XposedHook.handleLoadPackage(XposedHook.java:122)
09-18 09:54:59.639 E/Xposed  (30569): 	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:34)
09-18 09:54:59.639 E/Xposed  (30569): 	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61)
09-18 09:54:59.639 E/Xposed  (30569): 	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:106)
09-18 09:54:59.639 E/Xposed  (30569): 	at de.robv.android.xposed.XposedInit$1.beforeHookedMethod(XposedInit.java:93)
09-18 09:54:59.639 E/Xposed  (30569): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:314)
09-18 09:54:59.639 E/Xposed  (30569): 	at android.app.ActivityThread.handleBindApplication(<Xposed>)
09-18 09:54:59.639 E/Xposed  (30569): 	at android.app.ActivityThread.access$1500(ActivityThread.java:178)
09-18 09:54:59.639 E/Xposed  (30569): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1531)
09-18 09:54:59.639 E/Xposed  (30569): 	at android.os.Handler.dispatchMessage(Handler.java:111)
09-18 09:54:59.639 E/Xposed  (30569): 	at android.os.Looper.loop(Looper.java:194)
09-18 09:54:59.639 E/Xposed  (30569): 	at android.app.ActivityThread.main(ActivityThread.java:5637)
09-18 09:54:59.639 E/Xposed  (30569): 	at java.lang.reflect.Method.invoke(Native Method)
09-18 09:54:59.639 E/Xposed  (30569): 	at java.lang.reflect.Method.invoke(Method.java:372)
09-18 09:54:59.639 E/Xposed  (30569): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
09-18 09:54:59.639 E/Xposed  (30569): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)
09-18 09:54:59.639 E/Xposed  (30569): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
09-18 09:54:59.639 E/Xposed  (30569): Caused by: java.lang.ClassNotFoundException: com.android.systemui.statusbar.policy.MobileSignalController
09-18 09:54:59.639 E/Xposed  (30569): 	at java.lang.Class.classForName(Native Method)
09-18 09:54:59.639 E/Xposed  (30569): 	at java.lang.Class.forName(Class.java:309)
09-18 09:54:59.639 E/Xposed  (30569): 	at external.org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:823)
09-18 09:54:59.639 E/Xposed  (30569): 	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:62)
09-18 09:54:59.639 E/Xposed  (30569): 	... 20 more
09-18 09:54:59.639 E/Xposed  (30569): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.systemui.statusbar.policy.MobileSignalController" on path: DexPathList[[zip file "/system/priv-app/SystemUI/SystemUI.apk"],nativeLibraryDirectories=[/vendor/lib64, /system/lib64]]
09-18 09:54:59.639 E/Xposed  (30569): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
09-18 09:54:59.639 E/Xposed  (30569): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
09-18 09:54:59.639 E/Xposed  (30569): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
09-18 09:54:59.639 E/Xposed  (30569): 	... 24 more
09-18 09:54:59.639 E/Xposed  (30569): 	Suppressed: java.lang.ClassNotFoundException: Didn't find class "com.android.systemui.statusbar.policy.MobileSignalController" on path: DexPathList[[dex file "/data/dalvik-cache/xposed_XResourcesSuperClass.dex"],nativeLibraryDirectories=[/vendor/lib64, /system/lib64]]
09-18 09:54:59.639 E/Xposed  (30569): 		at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
09-18 09:54:59.639 E/Xposed  (30569): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
09-18 09:54:59.639 E/Xposed  (30569): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
09-18 09:54:59.639 E/Xposed  (30569): 		... 25 more
09-18 09:54:59.639 E/Xposed  (30569): 		Suppressed: java.lang.ClassNotFoundException: com.android.systemui.statusbar.policy.MobileSignalController
09-18 09:54:59.639 E/Xposed  (30569): 			at java.lang.Class.classForName(Native Method)
09-18 09:54:59.639 E/Xposed  (30569): 			at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
09-18 09:54:59.639 E/Xposed  (30569): 			at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
09-18 09:54:59.639 E/Xposed  (30569): 			at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
09-18 09:54:59.639 E/Xposed  (30569): 			... 26 more
09-18 09:54:59.639 E/Xposed  (30569): 		Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
```

When I try to use latest experimental version, it crashes everytime i turn on the phone. I cant get log from that.

**Comment by paphonbth** [comment]
This issue has been fixed. Please get logs from the latest build.

**Comment by LosTigeros** [comment]
I cant get logs from latest build. When I try to power on the phone with latest app build, systemui instantly crashes.

**Comment by paphonbth** [comment]
Use adb. I can't fix your problem without knowing what's wrong.

**Comment by wasdennnoch** [comment]
Google "How to logcat" to find instructions on how to get a logcat via your computer.

**Comment by LosTigeros** [comment]
I know how to logcat ;) Wait, while. I'll try to get a logcat.

**Comment by wasdennnoch** [comment]
Normally the SystemUI shouldn't be able to change the adb connection. It can change how the phone talks to the phone (like MTP or PTP or Charge), but normally not adb related things. Or you have a weird phone :P

**Comment by LosTigeros** [comment]
After connect.
D:\Windows 10\Program Files (x86)\Android\android-sdk\platform-tools>adb devices
List of devices attached
5DV4AYGEIV9PKZ95        device

After few seconds.
D:\Windows 10\Program Files (x86)\Android\android-sdk\platform-tools>adb devices
List of devices attached
5DV4AYGEIV9PKZ95        offline

**Comment by LosTigeros** [comment]
Okay I have it!
http://pastebin.com/raw/QTwpJGgh

**Comment by wasdennnoch** [comment]
How'd you manage to get an Xposed log lol. But I can imagie that the error in there causes the crash. I just uploaded a new snapshot which should contain a fix, see the new link in the 2nd post in the XDA thread.

**Comment by LosTigeros** [comment]
I get it from /data/data/de.robv.android.xposed.installer/log/error.log.old ;)

**Comment by LosTigeros** [comment]
It still crashes systemui on startup
http://pastebin.com/raw/BHvD5D8Z

**Comment by wasdennnoch** [comment]
Should already be fixed.

**Comment by LosTigeros** [comment]
Still crashes:
http://pastebin.com/raw/VaJqjWED

http://pastebin.com/raw/f2Zi1RR3

**Comment by LosTigeros** [comment]
I can give you deodexed systemui apk if you want.

**Comment by wasdennnoch** [comment]
That would be greas as I've never heared of your phone before. Sorry for the late reply, I'm back fixing things ;)

**Comment by LosTigeros** [comment]
So here it is: https://gamecentrum.pl/own/SystemUI.apk

**Comment by wasdennnoch** [comment]
Should be fixed with 0ab575c42e6532a081100cec9c7fd212e5c79a05 (build 728).
