### ISSUE TITLE
Date clipping problem

### ISSUE THREAD

**Issue by sargijeh** [wasdennnoch/AndroidN-ify#947]
There is a problem with alignments of the date since the first build of this module :(
the date is a little down, and in some month like July, it shows the name like "Julv"!
it is some kind of cropped!
xposed logs are attached:

[xposed_error_20160924_012730.log.txt](https://github.com/wasdennnoch/AndroidN-ify/files/490756/xposed_error_20160924_012730.log.txt)

![screenshot_2016-09-24-01-26-53](https://cloud.githubusercontent.com/assets/22320438/18802603/aff87c34-81f6-11e6-9a96-31a4ac3ff90a.png)
![screenshot_2016-09-24-01-27-05](https://cloud.githubusercontent.com/assets/22320438/18802610/b3483bd6-81f6-11e6-8b03-7f4239500fae.png)

**Comment by wasdennnoch** [comment]
Would it be possible fo you to post a deodexed SystemUI? This would also fix an issue with the "x" mobile data indicator not showing from what I've seen in the logs.

**Comment by sargijeh** [comment]
I'm not deodexed, what can I do? And I can't find it on internet either.
Is it necessary for the clock alignment issue? @wasdennnoch

**Comment by paphonbth** [comment]
Fixed with #960.

**Comment by sargijeh** [comment]
@paphonbth my phone is ZUltra, it's the biggest phone not small screen!

**Comment by paphonbth** [comment]
Oops. Closed wrong one. Sorry.

**Comment by wasdennnoch** [comment]
Fixed with the commit with the wrong name. I disabled clipping of the text containers. 38c7445d1ce97877821cf61e5956d283710b328f

**Comment by sargijeh** [comment]
it's still there man :( on build 694 :( @wasdennnoch 
it's still the same:
here are my xposed logs:
[xposed_error_20160927_224627.log.txt](https://github.com/wasdennnoch/AndroidN-ify/files/496492/xposed_error_20160927_224627.log.txt)
![screenshot_2016-09-27-22-56-38](https://cloud.githubusercontent.com/assets/22320438/18888870/11903258-8507-11e6-89f1-7df01c311f2b.png)
![screenshot_2016-09-27-22-56-45](https://cloud.githubusercontent.com/assets/22320438/18888875/167e5466-8507-11e6-8cb5-3732cfb6feb1.png)
I'm on xperia ZUltra LP

**Comment by wasdennnoch** [comment]
Hm. Are you sure your font doesn't just have a short p? :P

**Comment by sargijeh** [comment]
I'm sure @wasdennnoch 
look at these screenshots they are for august!:
![screenshot_2016-08-27-23-44-07](https://cloud.githubusercontent.com/assets/22320438/18890096/c0d19d38-850c-11e6-84d2-d81ee0cfdcf1.png)
![screenshot_2016-08-27-23-44-00](https://cloud.githubusercontent.com/assets/22320438/18890099/c22cdbac-850c-11e6-86d0-53766202d484.png)

**Comment by wasdennnoch** [comment]
Still happening with the new header layout?

**Comment by sargijeh** [comment]
@wasdennnoch unfortunately, yes :(
