### ISSUE TITLE
SystemUI Force closes

### ISSUE THREAD

**Issue by cbdreinulldrei** [wasdennnoch/AndroidN-ify#950]
Logs:

https://drive.google.com/file/d/0B1vBh5lb8HhGTEQ3VTJZTlhtRVE/view?usp=drivesdk

Nothing in Xposed log

**Comment by cbdreinulldrei** [comment]
System is Moto X Play with Marshmallow 6.0.1

**Comment by cbdreinulldrei** [comment]
Can force crash by changing from portrait to landscape. Does not matter if QS are visible.

https://drive.google.com/file/d/0B1vBh5lb8HhGZ2d2d0k1bVhacHM/view?usp=drivesdk

**Comment by cbdreinulldrei** [comment]
Still present in build 684. Crashes on almost every change from portrait to landscape.

**Comment by cbdreinulldrei** [comment]
Still present in 686.

**Comment by wasdennnoch** [comment]
"Fixed" with 3e9dbdde9961a79e616b0ef801bd15708dd2bdf4. There may be soe artifacts in the tiles after rotation though. Please report back if there are some other issues related to that.

**Comment by cbdreinulldrei** [comment]
Still crashes in 695.

https://drive.google.com/file/d/0B1vBh5lb8HhGUkdKZEtPVHFTM2s/view?usp=drivesdk

**Comment by cbdreinulldrei** [comment]
Not sure if I can reopen this but still broken on my Moto X Play.
